/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "socket.h"
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <signal.h>

int sockfd;
void intHandler(int dummy);
void error(char * msg);

void
socket_prog_1(char *host, variables arguments, int choice, int sockfd)
{
	CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, SOCKET_PROG, SOCKET_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (choice == 1)
	{
		double *result = average_1(&arguments, clnt);
		if (result == NULL)
			clnt_perror(clnt, "Call Failed.");
		else {
			char buffer[100];
			double avg = *result;
			sprintf(buffer, "%0.2lf", avg);
			send(sockfd, buffer, sizeof(buffer), 0);
			}
		
	}
	else if (choice == 2)
	{
		minMax *result = min_max_1 (&arguments, clnt);
		if (result == NULL)
			clnt_perror(clnt, "Call Failed.");
		else {
			char buffer[100];
			sprintf(buffer, "Min: %d\n Max: %d\n", result->min, result->max);
		}
	}
	else if (choice == 3){
		ginomeno *result = multiply_1(&arguments, clnt);
		if (result == NULL)
			clnt_perror(clnt, "Call Failed.");
		else {
			char buffer[100];
			for (int i = 0; i < arguments.len; i++){
				sprintf(buffer, "%d", result->resultArray[i]);
				send(sockfd, buffer, sizeof(buffer), 0);
    		}
		}
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
int portno, clilen, n, done;
    struct sockaddr_in serv_addr, cli_addr;

    if(argc < 3) {
        printf ("usage: %s server_host sock_port\n", argv[0]);
        exit (1);
    }
    
    //Socket Configuration
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if(sockfd < 0)
        error("ERROR opening socket");
    bzero((char *) &serv_addr, sizeof(serv_addr));
    portno = atoi(argv[2]);
    serv_addr.sin_family = AF_INET;
    serv_addr.sin_port = htons(portno);
    serv_addr.sin_addr.s_addr = INADDR_ANY;

    if(bind(sockfd, (struct sockaddr *) &serv_addr, sizeof(serv_addr)) < 0)
        error("ERROR: on binding");
    listen(sockfd, 5);

    signal(SIGINT, intHandler);

    for(;;) {
        printf("Waiting for a connection.....\n");
        clilen = sizeof(cli_addr);
        int newsockfd = accept(sockfd, (struct sockaddr *) &cli_addr, &clilen);

        if(newsockfd < 0)
            error("ERROR: on accept");

        if(fork() == 0) {
			variables arguments;
            char buffer[100];
            close(sockfd);
            printf("Connected.\n");
        
            recv(newsockfd, buffer, sizeof(buffer), 0);
            //printf("buffer = %s \n", buffer, test);
            
            arguments.len = atoi(buffer);
            arguments.array_Y = (int *)malloc(arguments.len * sizeof(int));
            for (int i = 0; i < arguments.len; i++){
                recv(newsockfd, buffer, sizeof(buffer), 0);
                arguments.array_Y[i] = atoi(buffer);
                printf("Array %d = %d\n",i, arguments.array_Y[i]);
            }

            for (;;) {
                int choice;
                recv(newsockfd, buffer, sizeof(buffer), 0);
                choice = atoi(buffer);
                if (choice == 4) 
                    break;
                else if (choice == 3) {
                    recv(newsockfd, buffer, sizeof(buffer), 0);
                    arguments.a = atoi(buffer);
                }
				socket_prog_1(argv[1], arguments, choice, newsockfd);
            }
                }
        close(newsockfd);
    }    

    close(sockfd);
    exit (0);
}

void intHandler(int dummy) {
    close(sockfd);
    exit(0);
}

void error(char * msg) {
    perror(msg);
    exit(1);
}