/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "socket.h"

double *
average_1_svc(variables *argp, struct svc_req *rqstp)
{
	static double  result;

	int sum = 0;
	for (int i = 0; i < argp->len; i++)
	{
		sum += argp->array_Y[i];
	}
	result = (double)sum/argp->len;
	return &result;
}

minMax *
min_max_1_svc(variables *argp, struct svc_req *rqstp)
{
	static minMax  result;
	result.min = argp->array_Y[0];
	result.max = argp->array_Y[0];
	for (int  i = 1; i < argp->len; i++)
	{
		if (argp->array_Y[i] > result.max)
			result.max = argp->array_Y[i];

		if (argp->array_Y[i] < result.min)
			result.min = argp->array_Y[i];
	}
	


	return &result;
}

ginomeno *
multiply_1_svc(variables *argp, struct svc_req *rqstp)
{
	static ginomeno  result;

	result.resultArray = (int *)malloc(argp->len * sizeof(int));
	for (int i = 0; i < argp->len; i++)
	{
		result.resultArray[i] = argp->array_Y[i] * argp->a;
	}
	

	return &result;
}
