/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "socket.h"

bool_t
xdr_variables (XDR *xdrs, variables *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->array_Y.array_Y_val, (u_int *) &objp->array_Y.array_Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_minMax (XDR *xdrs, minMax *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ginomeno (XDR *xdrs, ginomeno *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->resultArray.resultArray_val, (u_int *) &objp->resultArray.resultArray_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
